debug: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: afsdb
    password: afsdb

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    schemas: portfolio
    user: portfolio_flyway
    password: portfolio_flyway
    url: jdbc:mysql://localhost:3306/portfolio

